EXCEL_FILE: 'points.xlsx'
CHESSBOARDS: # list
  # 0
  - SQUARE_SIZE: 0.2 # m
    SHAPE:
      ROWS: 3
      COLS: 3
    CENTER:
      EXCEL_INDEX: # zero-indexed
        ROW: 2
        COL: 0
      COORDINATE_3D:
        X: 0.0
        Y: 0.0
    CAMERA_IDS:
      - 0
      - 1
      - 2
  # 1
  - SQUARE_SIZE: 0.2 # m
    SHAPE:
      ROWS: 3
      COLS: 3
    CENTER:
      EXCEL_INDEX: # zero-indexed
        ROW: 2
        COL: 0
      COORDINATE_3D:
        X: 0.0
        Y: 0.0
    CAMERA_IDS:
      - 3
      - 4
      - 5
ALL_CAMERA_IDS: 
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
SHARED_INTRINSIC:
  USE_SHARED_INTRINSIC: false
  CAMERA_ID: 1
